export enum Udane {
  oznaczJakoDzienWolny = 'Dzień został oznaczony jako wolny',
  oznaczJakoDzienPracy = 'Dzień został oznaczony jako dzień pracy',
  przerwaZostalaDodana = 'Przerwa została dodana pomyślnie',
  dzienWolnyUtworzony = 'Dzien wolny został dodany',
  usuwaniePrzerwy = 'Przerwa została usunięta',
  usuwanieDniaWolnego = 'Dzień wolny został usunięty',
  logoZakladuZaktualizowane = 'Logo zakładu zostało zaktualizowane',
  bannerStronyZaktualizowany = 'Banner zakładu został zaktualizowany',
  wizytaZostalaOdwolana = 'Wizyta została odwołana',
  wizytaZostalaZarejestrowana = 'Wizyta została zarejestrowana',
  wizytaOznaczonaJakoWykonana = 'Wizyta została oznaczona jako wykonana',
  wizytaOznaczonaJakoNieWykonana = 'Wizyta została oznaczona jako nie wykonana',
  wizytaZostalaZmodyfikowana = 'Wizyta została zmodyfikowana',
  daneZostalyZapisane = 'Dane zostały zapisane',
  startAutoRenew = 'Auto odnawianie aktywności zakładu zostało włączone',
  stopAutoRenew = 'Auto odnawianie aktywności zakładu zostało wyłączone',
}
